name: Docker Image CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        service:
          [
            "file-store",
            "image-processor",
            "subscription-handler",
            "gateway",
            "webpage-host",
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load VAPID keys from secret
        if: matrix.service == 'webpage-host'
        id: vapid_keys
        env:
          VAPID_JSON: ${{ secrets.VAPID }}
        run: |
          echo "::set-output name=publicKey::$(echo $VAPID_JSON | jq -r '.publicKey')"

      - name: Update publicKey in App.vue
        if: matrix.service == 'webpage-host'
        run: |
          sed -i "s/const publicKey = \".*\";/const publicKey = \"${{ steps.vapid_keys.outputs.publicKey }}\";/" ./frontend/src/App.vue

      - name: Build frontend before webpage-host
        if: matrix.service == 'webpage-host'
        run: |
          docker buildx build ./frontend \
          --file ./frontend/Dockerfile \
          -o ./frontend/dist \
          --progress plain \
          --cache-from type=gha \
          --cache-to type=gha,mode=max

          mkdir ./backend/webpage-host/public && tar -xzf ./frontend/dist/dist.tar.gz -C ./backend/webpage-host/public

      - name: Build and push image
        run: |
          build_path="./backend/${{ matrix.service }}"
          dockerfile_path="./backend/${{ matrix.service }}/Dockerfile"

          docker buildx build "$build_path" \
            --file "$dockerfile_path" \
            --progress plain \
            --push \
            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}_cicdhf:latest \
            --cache-from type=gha \
            --cache-to type=gha,mode=max

  deploy:
    runs-on: self-hosted
    needs: build # This job will run after the 'build' job completes
    steps:
      - uses: actions/checkout@v4

      - name: Create vapid_secret dir
        run: mkdir ./server/vapid_secret

      - name: create VAPID.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "VAPID.json"
          json: ${{ secrets.VAPID }}
          dir: "./server/vapid_secret/"

      - name: Copy init files over SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "server"
          target: .

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd server
            chmod +x install-docker.sh
            ./install-docker.sh
            mkdir images
            mkdir subscriptions
            mkdir vapid_secret
            docker compose pull
            docker compose up -d
