name: Docker Image CI CD action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --progress plain -o build
      - name: Rename files
        run: datetime=$(TZ=Europe/Budapest date -Iseconds); for file in ./build/*.pdf; do mv "$file" "${file%.pdf}"_$datetime.pdf; done
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          file: "build/documentation.pdf"
