name: Docker Image CI CD action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Build the Docker image
        run: docker buildx build ./doc --file ./doc/Dockerfile --progress plain -o doc_build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache

      - name: Rename files
        run: datetime=$(TZ=Europe/Budapest date -Iseconds); for file in ./doc_build/*.pdf; do mv "$file" "${file%.pdf}"_$datetime.pdf; done

      - name: Upload binaries to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/*.pdf"
          prerelease: false
          draft: false
